### ISSUE TITLE
Notifications cleaner but won't show on Google Maps 

### ISSUE THREAD

**Issue by paperc07** [jxmorris12/PokemonGo-Finder#31]
It's definitely cleaner recieveing the pushbullet notifications, but now when I click on the generated link it doesn't put anything on my Google map app on my phone it was working yesterday.

**Comment by bobsage123** [comment]
Same here. It opens to a blank google maps.

**Comment by KowabungaCheese** [comment]
If you replace with the following code in notifier.py, the link should work again. Not sure what fix they will implement but this works on the notification.

Make sure you use 4 spaces instead of TAB as well. Good luck out there!
Line 58:
replace: google_maps_link = 'http://maps.google.com/maps/place/{}/@{},{}z'.format(latLon, latLon, 20)
with     : google_maps_link = 'http://maps.google.com/maps?q={}&{}z'.format(latLon, 20);

**Comment by paperc07** [comment]
wow thank you so much @LukeTweed

**Comment by bobsage123** [comment]
Worked perfectly @LukeTweed. Thanks!

**Comment by jxmorris12** [comment]
thanks dude

**Comment by jxmorris12** [comment]
fixed this
